apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: demo
spec:
  selector:
    app: restaurant-app
  type: NodePort
  ports:
  - nodePort: 30002
    port: 8080
    targetPort: 2000
