apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    app: restaurant-app
spec:
  type: LoadBalancer
  selector:
    app: restaurant-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80